### ISSUE TITLE
Config Docker demo

### ISSUE THREAD

**Issue by cbouvat** [ffhandisport/ffh-filament-demo#1]

**Comment by cbouvat** [comment]
C'est fait a tester !

**Comment by cbouvat** [comment]
@matthieuLabaune @samuel-ginot Vous avez pu tester ?

**Comment by cbouvat** [comment]
Pas de nouvelles = bonne nouvelle ?

**Comment by matthieuLabaune** [comment]
@cbouvat pas pu tester filament sur notre appli de mon côté.
Je laisse @samuel-ginot répondre.
